a=input("enter a 1st number")
b=input("enter a 2nd number")
#print(int(a))
#print(int(b))
print("a+b:-",a+b)
print("a-b:-",a-b)
print("a*b:-",a*b)
print("a/b:-",a/b)
print("a%b:-",a%b)
print("a**b:-",a**b)
print("a//b:-",a//b)